### ISSUE TITLE
🏝️ Feature Request: Anti-Steal/Swap, give gold to other player

### ISSUE THREAD

**Issue by CARNONCODES** [The-Blooket-Hacks/Blooket-Hacks#104]
### Contact Details

casesciba1@gmail.com

### Gamemode

Gold Quest

### Requested function

A code that does not let people steal from you. And a code that gives gold to other players. 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
Okay... Certainly an interesting concept. We'll look into this, thank you 😃

**Comment by AlbumanO** [comment]
Yes that would be amazing!! Also this rel should be at the top nice job!!
