### ISSUE TITLE
🏝️ Feature Request: 

### ISSUE THREAD

**Issue by popingmom** [The-Blooket-Hacks/Blooket-Hacks#132]
### Contact Details

Ajrembert@icloud.com

### Gamemode

Tower of defense 2

### Requested function

 That I have infinite booket coins

### Any existing code

```JavaScript
Thanks
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CrazyH2** [comment]
Use this: https://github.com/The-Blooket-Hacks/Blooket-Hacks/blob/main/Tower%20Defense%202/Infinite%20Coins.js
I have already made this hack! :)

**Comment by popingmom** [comment]
I’m on iOS I need Instructions
