### ISSUE TITLE
🏝️ Feature Request: 

### ISSUE THREAD

**Issue by pugls12** [The-Blooket-Hacks/Blooket-Hacks#135]
### Contact Details

Puglsytt@gmail.com

### Gamemode

GimKit

### Requested function

Auto answer

### Any existing code

```JavaScript
Could u make it a bookmarklet
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CrazyH2** [comment]
I am remaking everything again so right now sorry I cant too busy
