### ISSUE TITLE
🏝️ Feature Request: 

### ISSUE THREAD

**Issue by PlatypusExplorer** [The-Blooket-Hacks/Blooket-Hacks#136]
### Contact Details

godofplatypuses@gmail.com

### Gamemode

gui for all or tower defence 1 and 2

### Requested function

infinite coins and instant kill and change the wave  number

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CrazyH2** [comment]
I am making a chrome extension at the moment please wait for me to finish as i am very busy
