### ISSUE TITLE
🏝️ Feature Request: 

### ISSUE THREAD

**Issue by Bnsjiso** [The-Blooket-Hacks/Blooket-Hacks#138]
### Contact Details

async () => {     let n = document.createElement('iframe');     document.body.append(n);     window.alert = n.contentWindow.alert.bind(window);     window.prompt = n.contentWindow.prompt.bind(window);     window.confirm = n.contentWindow.confirm.bind(window);     n.remove();             function reactHandler() {                 return Object.values(document.querySelector('#app > div > div'))[1].children[1]._owner;             };                      if (window.location.pathname != '/play/fishing') {                 alert('You must be in a fishing frenzy game!');             } else {                 let lure = Number(parseFloat(prompt('What do you want to set your lure to? (1 - 5)'))) - 1;                 reactHandler().stateNode.setState({ lure: lure < 0 ? 0 : lure > 4 ? 4 : lure });                          alert('Lure set!');             }; })();   function footer() {     let element = document.createElement('div');      element.style = `font-family: "Nunito", sans-serif; font-size: 14px; height: 65px; width: 175px; border: 4px solid rgb(15, 15, 15); background: rgb(240, 240, 240); position: absolute; top: 20x; left: 20px; border-radius: 10px; color: rgb(0, 0, 0); text-align: center;`;     element.innerHTML = `<p>Made by gliz <br> My <a style="color: #0000ff;" href="https://twitter.com/glizuwu" target="_blank">twitter</a></p>`;     document.body.appendChild(element);          var pos1 = 0, pos2 = 0, pos3 = 0, pos4 = 0;     element.onmousedown = ((e = window.event) => {         e.preventDefault();         pos3 = e.clientX;         pos4 = e.clientY;         document.onmouseup = (() => {             document.onmouseup = null;             document.onmousemove = null;         });         document.onmousemove = ((e) => {             e = e || window.event;             e.preventDefault();             pos1 = pos3 - e.clientX;             pos2 = pos4 - e.clientY;             pos3 = e.clientX;             pos4 = e.clientY;             let top = (element.offsetTop - pos2) > 0 ? (element.offsetTop - pos2) : 0;             let left = (element.offsetLeft - pos1) > 0 ? (element.offsetLeft - pos1) : 0;             element.style.top = top + "px";             element.style.left = left + "px";

### Gamemode

async () => {     let n = document.createElement('iframe');     document.body.append(n);     window.alert = n.contentWindow.alert.bind(window);     window.prompt = n.contentWindow.prompt.bind(window);     window.confirm = n.contentWindow.confirm.bind(window);     n.remove();             function reactHandler() {                 return Object.values(document.querySelector('#app > div > div'))[1].children[1]._owner;             };                      if (window.location.pathname != '/play/fishing') {                 alert('You must be in a fishing frenzy game!');             } else {                 let lure = Number(parseFloat(prompt('What do you want to set your lure to? (1 - 5)'))) - 1;                 reactHandler().stateNode.setState({ lure: lure < 0 ? 0 : lure > 4 ? 4 : lure });                          alert('Lure set!');             }; })();   function footer() {     let element = document.createElement('div');      element.style = `font-family: "Nunito", sans-serif; font-size: 14px; height: 65px; width: 175px; border: 4px solid rgb(15, 15, 15); background: rgb(240, 240, 240); position: absolute; top: 20x; left: 20px; border-radius: 10px; color: rgb(0, 0, 0); text-align: center;`;     element.innerHTML = `<p>Made by gliz <br> My <a style="color: #0000ff;" href="https://twitter.com/glizuwu" target="_blank">twitter</a></p>`;     document.body.appendChild(element);          var pos1 = 0, pos2 = 0, pos3 = 0, pos4 = 0;     element.onmousedown = ((e = window.event) => {         e.preventDefault();         pos3 = e.clientX;         pos4 = e.clientY;         document.onmouseup = (() => {             document.onmouseup = null;             document.onmousemove = null;         });         document.onmousemove = ((e) => {             e = e || window.event;             e.preventDefault();             pos1 = pos3 - e.clientX;             pos2 = pos4 - e.clientY;             pos3 = e.clientX;             pos4 = e.clientY;             let top = (element.offsetTop - pos2) > 0 ? (element.offsetTop - pos2) : 0;             let left = (element.offsetLeft - pos1) > 0 ? (element.offsetLeft - pos1) : 0;             element.style.top = top + "px";             element.style.left = left + "px";

### Requested function

async () => {     let n = document.createElement('iframe');     document.body.append(n);     window.alert = n.contentWindow.alert.bind(window);     window.prompt = n.contentWindow.prompt.bind(window);     window.confirm = n.contentWindow.confirm.bind(window);     n.remove();             function reactHandler() {                 return Object.values(document.querySelector('#app > div > div'))[1].children[1]._owner;             };                      if (window.location.pathname != '/play/fishing') {                 alert('You must be in a fishing frenzy game!');             } else {                 let lure = Number(parseFloat(prompt('What do you want to set your lure to? (1 - 5)'))) - 1;                 reactHandler().stateNode.setState({ lure: lure < 0 ? 0 : lure > 4 ? 4 : lure });                          alert('Lure set!');             }; })();   function footer() {     let element = document.createElement('div');      element.style = `font-family: "Nunito", sans-serif; font-size: 14px; height: 65px; width: 175px; border: 4px solid rgb(15, 15, 15); background: rgb(240, 240, 240); position: absolute; top: 20x; left: 20px; border-radius: 10px; color: rgb(0, 0, 0); text-align: center;`;     element.innerHTML = `<p>Made by gliz <br> My <a style="color: #0000ff;" href="https://twitter.com/glizuwu" target="_blank">twitter</a></p>`;     document.body.appendChild(element);          var pos1 = 0, pos2 = 0, pos3 = 0, pos4 = 0;     element.onmousedown = ((e = window.event) => {         e.preventDefault();         pos3 = e.clientX;         pos4 = e.clientY;         document.onmouseup = (() => {             document.onmouseup = null;             document.onmousemove = null;         });         document.onmousemove = ((e) => {             e = e || window.event;             e.preventDefault();             pos1 = pos3 - e.clientX;             pos2 = pos4 - e.clientY;             pos3 = e.clientX;             pos4 = e.clientY;             let top = (element.offsetTop - pos2) > 0 ? (element.offsetTop - pos2) : 0;             let left = (element.offsetLeft - pos1) > 0 ? (element.offsetLeft - pos1) : 0;             element.style.top = top + "px";             element.style.left = left + "px";

### Any existing code

```JavaScript
async () => {
    let n = document.createElement('iframe');
    document.body.append(n);
    window.alert = n.contentWindow.alert.bind(window);
    window.prompt = n.contentWindow.prompt.bind(window);
    window.confirm = n.contentWindow.confirm.bind(window);
    n.remove();
            function reactHandler() {
                return Object.values(document.querySelector('#app > div > div'))[1].children[1]._owner;
            };
        
            if (window.location.pathname != '/play/fishing') {
                alert('You must be in a fishing frenzy game!');
            } else {
                let lure = Number(parseFloat(prompt('What do you want to set your lure to? (1 - 5)'))) - 1;
                reactHandler().stateNode.setState({ lure: lure < 0 ? 0 : lure > 4 ? 4 : lure });
        
                alert('Lure set!');
            };
})();


function footer() {
    let element = document.createElement('div');

    element.style = `font-family: "Nunito", sans-serif; font-size: 14px; height: 65px; width: 175px; border: 4px solid rgb(15, 15, 15); background: rgb(240, 240, 240); position: absolute; top: 20x; left: 20px; border-radius: 10px; color: rgb(0, 0, 0); text-align: center;`;
    element.innerHTML = `<p>Made by gliz <br> My <a style="color: #0000ff;" href="https://twitter.com/glizuwu" target="_blank">twitter</a></p>`;
    document.body.appendChild(element);
    
    var pos1 = 0, pos2 = 0, pos3 = 0, pos4 = 0;
    element.onmousedown = ((e = window.event) => {
        e.preventDefault();
        pos3 = e.clientX;
        pos4 = e.clientY;
        document.onmouseup = (() => {
            document.onmouseup = null;
            document.onmousemove = null;
        });
        document.onmousemove = ((e) => {
            e = e || window.event;
            e.preventDefault();
            pos1 = pos3 - e.clientX;
            pos2 = pos4 - e.clientY;
            pos3 = e.clientX;
            pos4 = e.clientY;
            let top = (element.offsetTop - pos2) > 0 ? (element.offsetTop - pos2) : 0;
            let left = (element.offsetLeft - pos1) > 0 ? (element.offsetLeft - pos1) : 0;
            element.style.top = top + "px";
            element.style.left = left + "px";
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bnsjiso** [comment]
How do you add the hacks if you are on ipad

**Comment by src-ry** [comment]
:octocat:

**Comment by src-ry** [comment]
plz add actual details about what this is for so we dont read arbitrary javascript code

**Comment by CrazyH2** [comment]
> How do you add the hacks if you are on ipad

bookmarklets
