### ISSUE TITLE
🏝️ Feature Request: 

### ISSUE THREAD

**Issue by eksisme** [The-Blooket-Hacks/Blooket-Hacks#179]
### Contact Details

smithemm002@stu.asd103.org

### Gamemode

halloween candy

### Requested function

that i have infanite money

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by isaiahforney** [comment]
19158851915885

**Comment by isaiahforney** [comment]
1915885

**Comment by eksisme** [comment]
dont message me
