### ISSUE TITLE
🏝️ Feature Request: blooket hacks

### ISSUE THREAD

**Issue by PythonNerd12** [The-Blooket-Hacks/Blooket-Hacks#186]
### Contact Details

omartiradojr@gmail.com

### Gamemode

no gamemode

### Requested function

that i have infinite tokens 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PythonNerd12** [comment]
hi

**Comment by CrazyH2** [comment]
not possible
