### ISSUE TITLE
🪲 Bug: auto answer in battle royale closes tab

### ISSUE THREAD

**Issue by Lack-Of-Name** [The-Blooket-Hacks/Blooket-Hacks#51]
### Contact Details

swebst27@igs.vic.edu.au

### Hacks used

Battle Royale\Autoclick answers

### What happened?

pasted in the script as usual (in the lobby to the gamemode) and once the game started, it asked if I wanted to leave the page, pressing cancel leaves the screen white, and leaving leaves the page

### What browsers are you seeing the problem on?

Chromium based

### Relevant console errors

```JavaScript
none, the console showed what was coded for it to show on success
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Thing3487** [comment]
> ### Contact Details
> [swebst27@igs.vic.edu.au](mailto:swebst27@igs.vic.edu.au)
> 
> ### Hacks used
> Battle Royale\Autoclick answers
> 
> ### What happened?
> pasted in the script as usual (in the lobby to the gamemode) and once the game started, it asked if I wanted to leave the page, pressing cancel leaves the screen white, and leaving leaves the page
> 
> ### What browsers are you seeing the problem on?
> Chromium based
> 
> ### Browser
> _No response_
> 
> ### Relevant console errors
> ```js
> none, the console showed what was coded for it to show on success
> ```
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Stop using these hacks, they are stolen, use the original version by clicking [here](https://github.com/Minesraft2/Blooket-Cheats)
